### ISSUE TITLE
Make sure LANG is set to EN

### ISSUE THREAD

**Issue by mugraph** [dnaeon/makefile-graph#2]
In cases where `make` generates the db with non-english headers, the parser will never jump to https://github.com/dnaeon/makefile-graph/blob/08714cbb43f05f93c630c1a572a93ee23013bbc2/pkg/parser/parser.go#L47. Consequently, the generated SVG will be empty.

Maybe simply add that to the docs.

Thank you for your work <3!!

**Comment by dnaeon** [comment]
@mugraph , just pushed a fix for this.

https://github.com/dnaeon/makefile-graph/commit/4ed05420ce2c3921a52849bcaecef52c176609c9

Thanks!
